/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as HelpRouteImport } from './routes/help'
import { Route as JoinRouteImport } from './routes/join'
import { Route as RelationshipRouteImport } from './routes/relationship'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as TreeRouteImport } from './routes/tree'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminSubmissionsRouteImport } from './routes/admin/submissions'
import { Route as AdminTreeRouteImport } from './routes/admin/tree'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipRoute = RelationshipRouteImport.update({
  id: '/relationship',
  path: '/relationship',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeRoute = TreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTreeRoute = AdminTreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/relationship': typeof RelationshipRoute
  '/search': typeof SearchRoute
  '/statistics': typeof StatisticsRoute
  '/tree': typeof TreeRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/tree': typeof AdminTreeRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/relationship': typeof RelationshipRoute
  '/search': typeof SearchRoute
  '/statistics': typeof StatisticsRoute
  '/tree': typeof TreeRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/tree': typeof AdminTreeRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/relationship': typeof RelationshipRoute
  '/search': typeof SearchRoute
  '/statistics': typeof StatisticsRoute
  '/tree': typeof TreeRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/tree': typeof AdminTreeRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/help'
    | '/join'
    | '/relationship'
    | '/search'
    | '/statistics'
    | '/tree'
    | '/admin/members'
    | '/admin/submissions'
    | '/admin/tree'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/join'
    | '/relationship'
    | '/search'
    | '/statistics'
    | '/tree'
    | '/admin/members'
    | '/admin/submissions'
    | '/admin/tree'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/help'
    | '/join'
    | '/relationship'
    | '/search'
    | '/statistics'
    | '/tree'
    | '/admin/members'
    | '/admin/submissions'
    | '/admin/tree'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  HelpRoute: typeof HelpRoute
  JoinRoute: typeof JoinRoute
  RelationshipRoute: typeof RelationshipRoute
  SearchRoute: typeof SearchRoute
  StatisticsRoute: typeof StatisticsRoute
  TreeRoute: typeof TreeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationship': {
      id: '/relationship'
      path: '/relationship'
      fullPath: '/relationship'
      preLoaderRoute: typeof RelationshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree': {
      id: '/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof TreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tree': {
      id: '/admin/tree'
      path: '/tree'
      fullPath: '/admin/tree'
      preLoaderRoute: typeof AdminTreeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminMembersRoute: typeof AdminMembersRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminTreeRoute: typeof AdminTreeRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminMembersRoute: AdminMembersRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminTreeRoute: AdminTreeRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  HelpRoute: HelpRoute,
  JoinRoute: JoinRoute,
  RelationshipRoute: RelationshipRoute,
  SearchRoute: SearchRoute,
  StatisticsRoute: StatisticsRoute,
  TreeRoute: TreeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
